//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifikacion
    {
        public int Id_Specifikacion { get; set; }
        public int Material_Specifikacion { get; set; }
        public int Product_Specifikacion { get; set; }
        public decimal Kolvo { get; set; }
        public int EdIzm_Specifikacion { get; set; }
    
        public virtual EdiniciIzmereniya EdiniciIzmereniya { get; set; }
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}
