//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int Id_Zakaz { get; set; }
        public System.DateTime Date_Zakaza { get; set; }
        public int Zakazchik_Zakaz { get; set; }
        public int Product_Zakaz { get; set; }
        public int Kolvo { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Zakazchik Zakazchik { get; set; }
    }
}
