//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazchik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakazchik()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int Id_Zakazchiki { get; set; }
        public string Name_Zakazchiki { get; set; }
        public long Inn { get; set; }
        public string Adres { get; set; }
        public string Telephone { get; set; }
        public bool Prodavec { get; set; }
        public bool Pokupatel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
